<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="Verify market place is displayed" timestamp="2018-01-11T15:20:10" hostname="localhost" time="24.104" errors="0" tests="1" skipped="0" disabled="0" failures="0">
  <testcase classname="Verify market place is displayed" name="Open market place URL" time="24.097" />
 </testsuite>
 <testsuite name="Verify partner creation functionality" timestamp="2018-01-11T15:20:34" hostname="localhost" time="3.095" errors="0" tests="5" skipped="0" disabled="0" failures="3">
  <testcase classname="Verify partner creation functionality" name="Click partner with us link" time="0.147" />
  <testcase classname="Verify partner creation functionality" name="Click sign In link" time="0.201" />
  <testcase classname="Verify partner creation functionality" name="Verify that partner is able to create an account" time="1.259">
   <failure type="toEqual" message="Expected &apos;PARTNER WITH US&apos; to equal &apos;Partner Apps&apos;."><![CDATA[Error: Failed expectation
    at BaseClass.verifyTextIsEqualTo (D:\Jitendra\altone_qc\gui\commands\BaseClass.js:103:33)
    at MPPartnerWithUsPage.verifyPartnerSignIn (D:\Jitendra\altone_qc\gui\pages\HomePage1.js:51:18)
    at UserContext.<anonymous> (D:\Jitendra\altone_qc\gui\test_spec\a.js:47:28)
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1067:7)
    at ControlFlow.promise (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2396:12)
    at schedulerExecute (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)]]>
   </failure>
  </testcase>
  <testcase classname="Verify partner creation functionality" name="Verify that partner is able to add a new app" time="0.863">
   <failure type="exception" message="Failed: appData is not defined"><![CDATA[ReferenceError: appData is not defined
    at UserContext.<anonymous> (D:\Jitendra\altone_qc\gui\test_spec\a.js:52:44)
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1067:7)
    at ControlFlow.promise (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2396:12)
    at schedulerExecute (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2860:25)
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: Run it("Verify that partner is able to add a new app") in control flow
    at UserContext.<anonymous> (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:64:48
    at ControlFlow.emit (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\events.js:62:21)
    at ControlFlow.shutdown_ (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2565:10)
    at shutdownTask_.MicroTask (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2490:53)
From asynchronous test: 
Error
    at Suite.<anonymous> (D:\Jitendra\altone_qc\gui\test_spec\a.js:50:5)
    at addSpecsToSuite (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (D:\Jitendra\altone_qc\gui\test_spec\a.js:30:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)]]>
   </failure>
  </testcase>
  <testcase classname="Verify partner creation functionality" name="Verify that partner is able to edit app" time="0.621">
   <failure type="exception" message="Failed: appData is not defined"><![CDATA[ReferenceError: appData is not defined
    at UserContext.<anonymous> (D:\Jitendra\altone_qc\gui\test_spec\a.js:59:45)
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1067:7)
    at ControlFlow.promise (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2396:12)
    at schedulerExecute (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2860:25)
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: Run it("Verify that partner is able to edit app") in control flow
    at UserContext.<anonymous> (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:64:48
    at ControlFlow.emit (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\events.js:62:21)
    at ControlFlow.shutdown_ (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2565:10)
    at shutdownTask_.MicroTask (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2490:53)
From asynchronous test: 
Error
    at Suite.<anonymous> (D:\Jitendra\altone_qc\gui\test_spec\a.js:57:5)
    at addSpecsToSuite (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\Automators.""\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (D:\Jitendra\altone_qc\gui\test_spec\a.js:30:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>